
CREATE TABLE Inventario(
ID_Jugador INT PRIMARY KEY,
ID_Item INT NOT NULL,
CONSTRAINT FK_IDjug_Inv
FOREIGN KEY (ID_Jugador) REFERENCES Jugador(ID_Jugador)
CONSTRAINT FK_IDitem_Inv
FOREIGN KEY (ID_Item) REFERENCES Item(ID_Item)
);

CREATE TABLE Vendedor_NPC(
ID_Vendedor INT PRIMARY KEY
CONSTRAINT CH_NPC_5dig
CHECK (ID_Vendedor BETWEEN 10000 AND 99999)
);